version: "3.9"

services:
  api:
    build: .
    container_name: poke-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: poke-redis
    ports:
      - "6379:6379"

  test:
    build: .
    container_name: poke-tests
    command: pytest -v --disable-warnings
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - redis